### ISSUE TITLE
+ and * do not check type of single argument

### ISSUE THREAD

**Issue by lassik** [shirok/Gauche#1012]
```Scheme
> (+ '|2|)
|2|
> (* '|2|)
|2|

> (+ '|2| '|3|)
*** ERROR: operation + is not defined between |2| and |3|
> (* '|2| '|3|)
*** ERROR: operation * is not defined between |2| and |3|
```

**Comment by shirok** [comment]
It turned out it's not straightforward, though (maybe that's why I originally didn't implement type check in these cases).

Although not documented yet, Gauche has a way to extend arithmetic operators through generic functions.  In the expression `(+ X Y)` and at least one of the argument is not a `<number>`, it calls a generic function `object-+`.  By specializing `object-+`, you can let you own type to be used in the arithmetic expressions.  Gauche-gl uses this feature for matrix, vector, and quaternion arithmetics.

Unary `-` and unary `/` are also delegated to generic functions, but uniary `+` and unary `*` are not, for they would just be returning the arguments.

Now, I thought I can pass `(+ X)` if there's any two-argument `object-+` method defined that accept `X` in either argument.  But it turned out that if there's any method that accepts `<top>` in either argument, that check passes, although there's no specific method to handle the type of `X`.

The simplest way is to make unary `+` and `*` be delegated to generic functions as well.  Then the method provider can ensure they work on their types.  It does break backward compatibility, but it's undocumented anyway, it won't affect existing code too much (I hope).

The reason I haven't documented it yet is that I'm still ambivalent about this feature.  The big issue is that the effect of defining methods is global and can interfere between libraries.

**Comment by lassik** [comment]
Interesting. What is the most general mathematical structure on which arithmetic (addition, subtraction, multiplication, division) makes sense? Perhaps make that a superclass of number, vector, matrix, and quaternion? There are a few mathematicians on the SRFI lists who might be able to help.

**Comment by lassik** [comment]
(As you know, the Python approach of permitting any objects, e.g. `"foo" + "bar"`, has the problem that e.g. `2 + 3` is commutative but `"foo" + "bar"` is not. This seems iconsistent to people with mathematical training.)

**Comment by shirok** [comment]
Gauche reserves the rights to optimize based on the assumption of commutativity of addition (e.g. `(+ 1 x)` and `(+ x 1)` are compiled into the same code, regardless of the type of `x`).  The provider of enhanced arithmetics is expected to meet the assumption.

I regard the feature as an experiment laboarty.  It lets users try new abstraction ideas to see if it works well or not.   So, planning what objects would make sense for it beforehand is kind of defeating the purpose.

It might be desirable to formulate the basic rules such enhancement should follow.  Languages like Haskell are much suited for such discussion, though.  (By defining typeclass such as Group, Ring, or Field).

**Comment by shirok** [comment]
Now it warns.

```
gosh> (+ 'foo)
WARNING: operation + is not defined on foo.  This will be an error in future releases.
foo
```
