### ISSUE TITLE
Doc and release update planned?

### ISSUE THREAD

**Issue by xificurC** [shirok/Gauche#206]
Hi, I see there is ongoing development on gauche but it hasn't seen a doc or release update since summer 2014. Do you have any plans? I'm sure **some** things changed :)

**Comment by shirok** [comment]
I'm planning to wrap 0.9.5 after finishing srfi-128 support.  Because of infrequent releases, many active users tend to use development HEAD and I used that for my excuse of putting off releases... but year, I procrastinated that too long.

**Comment by xificurC** [comment]
Thanks for the quick response. Is there any place I can ask questions like this instead of opening github issues? IRC/gitter/slack/...? E.g.

- the `INSTALL.in` file says to run `./configure` but I don't see a file named like that. Is one supposed to run some other tool like `autoconf`? I'm not well versed in this area
- what are the build/runtime dependencies? Which ones are optional?
- would gauche run fine under musl libc?

**Comment by shirok** [comment]
Check HACKING for build instructions from the repo; you need to install latest release of Gauche from tarball in order to build from the repo because of bootstrapping.  The release tarball contains INSTALL which describes external dependencies.

You can subscribe gauche-devel ML.  See http://practical-scheme.net/gauche/ for info.

I vaguely remember somebody tried with musl libc, but can't recall if it was successful, neither find conversation in ML.  I guess the best bet is to ask on ML.

**Comment by xificurC** [comment]
Thank you very much
