### ISSUE TITLE
`begin' does not control the sequence of input/output

### ISSUE THREAD

**Issue by KelvinLu1024** [shirok/Gauche#252]
$ gosh -V
Gauche scheme shell, version 0.9.5 [utf-8,pthreads], x86_64-pc-linux-gnu
$ gosh -r7
gosh[r7rs.user]> (begin (display 1) (display (read)))
2 ;; <== my input
12#<undef>
gosh[r7rs.user]> 

I think gauche should print 1 before ask for input.

**Comment by shirok** [comment]
It's not the order of execution.  It's because output of '1' is buffered.  You have to flush it explicitly.

`(begin (display 1) (flush-output-port) (display (read)))`

I know the source of confusion, though.  In stdio library, stdin and stdout is linked in a way that "when input is read, buffered output is implicitly flushed beforehand".  Scheme implementations that uses the standard mechanism automatically get that behavior.   Gauche implements i/o from lower level, bypassing stdio, so there's no such implicit flushing.

I've seen this question arises several times, so I might consider mimicking stdio behavior.

**Comment by KelvinLu1024** [comment]
Thank you!
