### ISSUE TITLE
read-uvector! seems limited by 32bit amount of data

### ISSUE THREAD

**Issue by crocusino** [shirok/Gauche#368]
```
(use srfi-4)

(define v1 (make-f64vector 300000000)); larger than 2^28 items
(call-with-input-file "data.dat"
    (lambda (prt)
        (read-uvector! v1 prt 0 268435456))); i.e. 2^28 items == 2^31 Bytes => silently returns #<eof> !!!

;; WHILE
(call-with-input-file "data.dat"
    (lambda (prt)
        (read-uvector! v1 prt 0 268435455))); OK reads in the data
```

**Comment by shirok** [comment]
Thanks for pointing it out.  Turned out that we used int in lots of places where we should use size_t.  Curse of sloppy coding!

**Comment by shirok** [comment]
Hmm, the error does look like something caused by recent commits, but I can't reproduce it.  I also have Ubuntu 18.04/x86_64.  Can you tell me your configure option?  Also, do you directly build from git source tree, or you create tarball first then build from it?  If the latter is the case, which platform you create the tarball on?

**Comment by okuoku** [comment]
Configure option is just `./configure --prefix=PREFIX`, source tree was generated using the same host, [copy of Gauche 0.9.6](https://bitbucket.org/okuoku/yunibase-impl-stable/src/master/gauche/) + `./DIST gen`, configured again on the tree directly(no tarball). Build environment is on [Docker](https://github.com/okuoku/yunibase/blob/dda58a1d803257f5de42a0f980bc56d993d7cdf1/hosts/docker-linux/base-ubuntuLTS/Dockerfile) (on the hub `okuoku/yunibuild`)

So we are generating build tree directly from the latest release. Would it be better to do two-step bootstrap? (`0.9.6` → `HEAD` → `HEAD` again then install)

**Comment by shirok** [comment]
No, you shouldn't need two steps.  Build & install HEAD with 0.9.6 should be fine.

I'm trying to reproduce the symptom using docker.  When I run the docker image with your Dockerfile and build 0.9.6 from clone of yunibase-impl-repo, it barfs because of the timestamp (it thinks it needs to precompile *.scm files and fails because there's no running gosh).  How are you building it?  Do you start initial 0.9.6 install from tarball, which has correct timestamps?

**Comment by okuoku** [comment]
I couldn't reproduce with `./DIST tgz` archive from affected tree -- so i guess there's something different from standard build procedure on the Yunibase build system... (Filed https://github.com/okuoku/yunibase/issues/67 for investigate.)

**Comment by okuoku** [comment]
Uh, no, `LD_LIBRARY_PATH` unintentionally set during `make install` and it broke built (HEAD) Gauche.

By fixing it ( https://github.com/okuoku/yunibase/commit/0c96de1dc890393a431459fa55793668add69b93 ), HEAD revision installs flawlessly. Sorry for the noise!

(Setting `LD_LIBRARY_PATH` was required for bootstrap because Yunibase will install Gauche into non-standard path for its purpose. Since `LD_LIBRARY_PATH` favoured over standard ELF LD paths aside RPATH, i guess it picked up old(0.9.6) shared libraries instead of built ones.)

**Comment by crocusino** [comment]
Wow, thank you so much!
