### ISSUE TITLE
string-titlecase import from srfi 129 doesn't work

### ISSUE THREAD

**Issue by roklein** [shirok/Gauche#472]
When I 
`(import (only (srfi 129) string-titlecase))`
I get an error message:
```
*** ERROR: during processing :only clause: binding of string-titlecase isn't exported from #<module srfi.129>
    While compiling "(standard input)" at line 1: (import (only (srfi 129) string-titlecase))
Stack Trace:
_______________________________________
  0  (eval expr env)
        at "/usr/local/share/gauche-0.97/0.9.7/lib/gauche/interactive.scm":269

```

Importing other parts of srfi-129 works, though, e.g.
`(import (only (srfi 129) char-titlecase))`
and
`(import (only (srfi 129) char-title-case?))`

Likewise, importing e.g.  `concatenate` from srfi-1 works.

However, 
`(import (only (gauche unicode) string-titlecase))`
works.

I suspect, there may be some issue in the way  `(use gauche.unicode)` works (in gauche-0.97/0.9.7/lib/srfi-129.scm).

**Comment by shirok** [comment]
Good catch.  Transitive export (exporting imported bindings) doesn't work with import modifiers. I should catch this type of errors in test-module.  Fix pushed.

https://github.com/shirok/Gauche/commit/b06e9d1c79e14fa9b10471caca792b0de6ea2ce7

**Comment by shirok** [comment]
It came to me that this could be better handled in r7rs#import, though.  Gauche's import semantics can handle the original code (exporting the imported bindings):

```
(use srfi-129 :only (string-titlecase)) ; works
```

**Comment by shirok** [comment]
Got it.  The culprit is module inheritance and transitive export.
`(import (only (srfi 129) ..))` loads the module `srfi.129`, which inherits `srfi-129`, which exports `string-titlecase` imported from `gauche.unicode`.
If you import `srfi-129` directly the import qualifiers work.  However, if you import `srfi.129`, they don't.
We say it a bug, for if a module A inherits B and do nothing else, A must behave exactly like B as long as its internals aren't mutated later.

**Comment by shirok** [comment]
Commit https://github.com/shirok/Gauche/commit/53b950d671098096727369a187999a3b4cf734d5 fixes the root issue.
