### ISSUE TITLE
Load error "body doesn't match with lambda list"

### ISSUE THREAD

**Issue by pclouds** [shirok/Gauche#486]
Some background. I'm writing XCB bindings and generating lots of new functions and record types. At some point, I got

```
$ gosh -I. xcb.scm                                                                                                                                                             
*** ERROR: body doesn't match with lambda list: #<closure ((xcb-write-NoOperation #:G720) . _)>
    While loading "./xproto.scm" at line 11
    While compiling "./xcb.scm" at line 6: (use xproto-dyn)
    While loading "./xcb.scm" at line 6
```

This happens if I define new functions and records with a macro, or write all those to a new file and `(include "that-file")`. Interestingly if I embed the generated code directly (i.e. no "include") _and_ remove the top "begin" form, then it works.

Which makes me think this is not really my fault generating bad code (or I may have misunderstood how "begin" form should be used). The generated code looks like this

    (begin
      (define....
      (define....
  
All this code is available at https://gitlab.com/pclouds/gauche-xcb/tree/gauche-loading-problem xproto-gen.scm is the generated file, reformatted with emacs to make it barely readable. You can switch to using macro instead by importing xproto-dyn in xcb.scm insted of xproto.

If you don't want to mess with that repo, just let me know what you want me to do, I'll try it.

Tested with

    Gauche scheme shell, version 0.9.8 [utf-8,pthreads], x86_64-pc-linux-gnu

**Comment by shirok** [comment]
Hm, the message indicates there's some discrepancy in the internal expansion of method definition.  Will look into it.

**Comment by pclouds** [comment]
A data point if it helps. After deleting 35 define-method and 9 define, no more load error. Adding one back, error. Deleting define alone seems to work to after about 15.

**Comment by shirok** [comment]
I cloned the repo, run make and then run `gosh -I. xcb.scm` but it doesn't raise an error (it prints out #<xcb-struct-Setup ...> and exit).   Could it be dependent on X setting as well?

I pushed a change that prints more info in the error message.  Could you fetch Gauche HEAD and try to run again, and let me know the output?

**Comment by pclouds** [comment]
I think you're probably on 'master' branch which runs fine. If you switch to gauche-loading-problem branch, you could just run gosh (without "make"). Gauche HEAD shows this

```
*** ERROR: method body #<closure ((xcb-write-NoOperation #:G720) . _)> doesn't match with lambda list (obj port)
    While loading "./xproto.scm" at line 11
    While compiling "./xcb.scm" at line 6: (use xproto)
    While loading "./xcb.scm" at line 6
Stack Trace:
_______________________________________
```

which is weird. xcb-write-NoOperation does not take two arguments

```scheme
(define (xcb-write-NoOperation req)
    (parameterize ((write-count 0))
      (xcb-write-BYTE 127))
    (xcb-write-pad 1)
    (xcb-write-CARD16 1)
    #f)
```

"obj port" looks like one of those "define-method write-object", e.g.

```scheme
(define-method write-object ((obj xcb-request-NoOperation) port)
    (display "#<xcb-request-NoOperation" port)
    (display ">" port))
```

**Comment by pclouds** [comment]
..and if I update the code to _not_ generate any write-object methods, loading is ok!

**Comment by shirok** [comment]
Ah, OK.  I pulled the branch and can reproduce the error.

**Comment by shirok** [comment]
If you give -fno-lambda-lifting-pass flag it runs, which strongly suggests the bug is in Gauche's optimizer.

**Comment by shirok** [comment]
The `#<closure ((xcb-write-NoOperation #:G720) . _)>` is misleading.  It isn't actually related to `xcb-write-NoOperation`.  It's an independent procedure created as a result of lambda lifting, and Gauche tried to give its meaningful name, but because whole bunch of procedures are bundled together with `begin` it just chose the last one as the "parent" of the procedure.  You can ignore `xcb-write-NoOperation` part.

What appears to be happening is that the compiler lifts the body of write-object as an independent closure and passes it to add-method!, but somehow it is mixed up with another procedure.  Still keep looking into it.

**Comment by pclouds** [comment]
Thanks. That'll let me continue playing with X11 protocol. I'll just leave it to you to work your magic on those mysterious optimizers :)

**Comment by shirok** [comment]
I got it.  It's index overflow.  Lambda lifting pass creates a huge local environment (since all the lifted procedures in the `begin` form is gathered into one `letrec` form).  In xproto-gen's case, it has 1091 lifted closures.  However, Gauche's VM instruction can only index up to 1024 per environment.   The index is wrapped-around, so it fetches different closure than intended.

Thanks for pushing the limits of Gauche!  Now I'm thinking what's the best to fix this.

**Comment by pclouds** [comment]
I broke Gauche, woohoo!

**Comment by shirok** [comment]
I believe the right way to fix this issue is to avoid generating such large environment frame in the lambda-lifting pass; however, as a fallback, I added support of large environment frames in https://github.com/shirok/Gauche/commit/b93a737a47f38076fcef1545259fed91ea1517b7 .
The xproto-gen (with write-object methods) now loads.

**Comment by pclouds** [comment]
Thanks. I was actually not sure if rare cases like this justified a new vm instruction. Restricting the lambda lifting pass sounds like the right choice [1]. But I guess that new one does not add much more complexity to the compiler.

We should make sure though that index overflow is always caught (unless the check is too expensive) even with the large environment frames. In my case, I think if the wrapped index points to a lambda with the same signature, I probably would not see the error even though generated code is still wrong.

[1] but there should be a way for users to see that optimizations are turned off, or limited, because of this and that reason...

**Comment by shirok** [comment]
Large environment frame can be generated by macros and translators as well, so the previous limitation (1024) could be too small.  Now its up to 2^20-1 so it should cover most practical cases.  I also added the check of env frame size (in the next commit) so the compiler throws an error if the code exceeds the limit.

**Comment by shirok** [comment]
Commit 901afff also addresses the large local frame generated by lambda lifting pass.
