### ISSUE TITLE
Quote behavior with `(import (r7rs))` but without `-r 7`

### ISSUE THREAD

**Issue by lassik** [shirok/Gauche#513]
I wonder what causes this:

```
$ gosh -r 7
gosh[r7rs.user]> 'foo
foo
gosh[r7rs.user]> (import (r7rs))
gosh[r7rs.user]> 'foo
foo
gosh[r7rs.user]> (exit)

$ gosh
gosh> 'foo
foo
gosh> (import (r7rs))
gosh[r7rs.user]> 'foo
*** ERROR: unbound variable: foo
```

**Comment by lassik** [comment]
This happens in 0.9.8 and git master

**Comment by shirok** [comment]
It is because `r7rs` module doesn't export `quote`.  If you just say `(import (r7rs))` from the usual Gauche REPL (not from `r7rs.user`), two things happens:

- Since it is R7RS-style `import`, Gauche loads R7RS infrastructure and switches the environment to the vanilla R7RS environment.  Notably, in this enviornment, only `import` and `define-library` are recognized.
- It loads `(r7rs)` module (which isn't a part of R7RS, by the way---its Gauche-specific module name that defines R7RS infrastructure).  That module only exports `define-library`.

So, in the latter case, you can only use `import` and `define-library` in the `r7rs.user` prompt.

Then why you can use `quote` with `-r 7` option?  That's because with `-r 7` option, Gauche pre-imports a bunch of R7RS libraries for your convenience.  See "Using R7RS REPL" in the manual
http://practical-scheme.net/gauche/man/gauche-refe/R7RS-integration.html#R7RS-integration

The proper way to switch R7RS REPL from ordinary Gauche REPL is to import one of R7RS librarires, e.g. `(import (scheme base))`.  The `(scheme base)` library exports `quote`.

**Comment by lassik** [comment]
Thanks for explaining it. That makes sense. Would it be a problem if `(import (r7rs))` implicitly also imports `(scheme base)`?

**Comment by shirok** [comment]
My $.02 is just "don't import r7rs".  It should be considered as an under-the-hood infrastructure.  `(scheme base)` or other `(scheme <something>)` are what R7RS define.  That is, if you say `(import (r7rs))`, it's not a portable R7RS code.  The portable R7RS code should explicitly say `(import (scheme base))` etc.

That said, I see the name `r7rs` is a part of the reason of confusion.  I should name it so that it clearly show it's the infrastructure and not meant to be imported by user code.

**Comment by lassik** [comment]
Agreed, `r7rs` sounds ordinary enough that some newbies like me try to import it to use R7RS :) I've had things like `(import (r7rs) (scheme base))` before in scripts I've written in Gauche, but the lack of `quote` surprised me since it implements the `'` read syntax.

Changing the name of the library would surely be enough to avoid any confusion. Maybe something like `(gauche r7rs foundation)`... or `internal` or `low-level` or `define-import` - what would be a good word?

As one reference point, Chicken has an `(import (r7rs))` that imports lot of stuff and (I believe) allows the user to use most of the R7RS stuff (probably not all the syntax unless one starts `csi` in `-R r7rs` mode). Though it also prints lots of warnings about `re-importing already imported identifier: assoc´ etc. so it's probably also not meant to be used directly.

**Comment by lassik** [comment]
Thanks for the fix! Just tested it and `(import (r7rs-setup))` works as expected. However, I still get this:

```
$ gosh
gosh> *load-path*
("/Users/lassi/.local/share/gauche-0.97/site/lib"
 "/Users/lassi/.local/share/gauche-0.97/0.9.9_pre1/lib")
gosh> quote
#<syntax quote>
gosh> (import (r7rs))
gosh[r7rs.user]> quote
*** ERROR: unbound variable: quote
Stack Trace:
_______________________________________
  0  quote
        [unknown location]
  1  (eval expr env)
        at "/Users/lassi/.local/share/gauche-0.97/0.9.9_pre1/lib/gauche/interactive.scm":269
gosh[r7rs.user]>
$
$ find /Users/lassi/.local/share/gauche-0.97 -iname "*r7rs*"
/Users/lassi/.local/share/gauche-0.97/0.9.9_pre1/lib/compat/r7rs-srfi-tests.scm
/Users/lassi/.local/share/gauche-0.97/0.9.9_pre1/lib/r7rs-setup.scm
$
```

**Comment by shirok** [comment]
Ok, now you can't just say `(import (r7rs))`.

**Comment by lassik** [comment]
Cool, just tested master and it works. `gosh -r 7` works too. Thanks a lot for listening to feedback!
