### ISSUE TITLE
match expression (or :key1 :key2) does not work.

### ISSUE THREAD

**Issue by tsahara** [shirok/Gauche#547]
gosh cannot compile match expression `(or ...)` with 2 or more keywords.

```
% cat bad.scm
(use util.match)
(match :foo
  ((or :foo :bar) (print "=> :foo|:bar")))

% gosh bad.scm
*** ERROR: variables of or-pattern differ in (or :foo :bar)
    While compiling "./bad.scm" at line 2: (match :foo ((or :foo :bar) (print "=> :foo|:bar")))
    While loading "./bad.scm" at line 3
Stack Trace:
_______________________________________
```

`(or ...)` with a single keyword, 2 quoted keywords, or 2 strings works well.

```
% cat ok.scm
(use util.match)

(match :foo
  (:foo (print "=> :foo")))

(match :foo
  ((or ':foo ':bar) (print "=> :foo|:bar")))

(match "foo"
  ((or "foo" "bar") (print "=> \"foo\"|\"bar\"")))

cat% gosh ok.scm
=> :foo
=> :foo|:bar
=> "foo"|"bar"
```

tested on 0.9.8 and master:
 - `Gauche scheme shell, version 0.9.8 [utf-8,pthreads], x86_64-apple-darwin18.6.0`
 - `Gauche scheme shell, version 0.9.9_pre2 [utf-8,pthreads], x86_64-apple-darwin19.0.0`

**Comment by shirok** [comment]
It's because a keyword is just a symbol globally bound to itself.  So `(or :foo :bar)` is just the same as `(or variable1 variable2)`, hence any expression can match both `:foo` and `:bar`, which is ambiguous and `util.match` rejects it.

If you need to test the input is really `:foo` or `:bar`, match as literals: `(or ':foo ':bar)`.

See also  http://practical-scheme.net/gauche/man/?p=Keyword%20and%20symbol%20integration

**Comment by tsahara** [comment]
That makes sense.  Thank you for explaining in detail.
