### ISSUE TITLE
only modifier in import statements is not working

### ISSUE THREAD

**Issue by jgonis** [shirok/Gauche#549]
Hi there,

Thanks for all the great work you do with Gauche!

I have a minimal test case based around an error I discovered in a larger program of mine. Given two r7rs scheme files existing in the same directory, testLib.sld and testProg.sld:
```
(define-library (testLib)
   (export func1
           func2)    
  (import (scheme base))
  (begin
    (define func1
      (lambda (x)
        (* x 2)))
    (define func2
      (lambda (x)
        (* x 3)))))
```

and 
```
(include "testLib.sld")
(define-library (testProg)
  (export prog)
  (import (scheme base)
          (only (testLib) func1))
  (begin
    (define prog
      (lambda (x)
        (func1 x)))))
```

trying to include testProg.sld from the repl as follows `(include "testProg.sld")` gives the following error: 
``` *** ERROR: during processing :only clause: binding of func1 isn't exported from #<module testLib>
    While compiling "(standard input)" at line 1: (include "testProg.sld")
Stack Trace:
_______________________________________
  0  (eval expr env)
        at "c:\\Program Files\\Gauche\\share\\gauche-0.97\\0.9.8\\lib/gauche/interactive.scm":269 
```

If I remove the only clause in the import statement from testProg.sld everything works great.

**Comment by shirok** [comment]
Hmm, looks like compile phase timing issue.

If you just load testProg.sld , it works.  (e.g `(load "./testProg.sld")` in REPL).   `include` replaces itself with the content of the file wrapped by `begin`.  Gauche compiles each toplevel form separately and executes it, but if wrapped with begin, the entire forms are compiled at once.  When the only form is compiled it checks the binding of the given symbol(s) exist in the imported module.  However, in this case, the imported module (testLib) but it hasn't been executed, so the runtime binding of `func1` doesn't exist yet.

The semantically right thing would probably be to let `define` reserves the binding at compile time (the actual value won't be calculated until it is executed).

Meanwhile, the workaround would be to split including testProg and testLib,

**Comment by jgonis** [comment]
Sure things, thanks for the reply. My knowledge of scheme isn't super complete so I wasn't sure what the "best practices" way of bringing a file into the repl was. I used include just out of habit, but reading through the r7rs spec maybe load is the more correct way to do this.

**Comment by jgonis** [comment]
Just a quick follow up, the `load` workaround only works when the chain of include statements is 1 deep I think? I tried to use that on my larger project and still got the error.  

The project is structured as follows: I am working through the book The Seasoned Schemer and I have a top level `tests.sld` file that `include`s test files for each chapter of the book, which contain unit tests around the code I write. The top-level file invokes all the tests for each chapter so I can run all my tests repeatedly with each change. `testCh1.sld` would be the tests for code from chapter 1.  This test file, `testCh1.sld` then `include`s the implementation file `seasonedSchemerCh1.sld` which contains that code for that chapter of the book.  This file then contains `include`s to implementation files for the book The Little Schemer, as some of the utility functions are re-used, so it contains `(include "littleSchemerCh1.sld")` as an example.

In this case invoking `(load "tests.sld")` fails with the same error as I was seeing originally.

**Comment by shirok** [comment]
Right, the issue is `include` expands into `begin` with multiple modules in it, and REPL is irrelevant.

However, `include` is only needed if you want to expand the contents here.  Most popular use is that you write library declaration in .sld file, and include the implementation code--which doesn't have `define-library` stuff, and only the scheme declarations.

You don't really need `(include "testLib.sld")` in your minimal case above, since `(import (testLib))` automatically loads "testLib.sld".   The only thing is that you need to make sure "testLib.sld" placed in the load path (in Gauche, variable `*load-path*` keeps the current load path).  The load path doesn't include the current directory, so you would need to invoke gosh as `gosh -I.` if you want to load from the current directory.

**Comment by jgonis** [comment]
So if I understand is the recommended way to structure this sort of project, to generally avoid the use of include and rely on the load path being set correctly so that import statements bring in the correct library definitions and proceed that way? It's hard to find a best practices for r7rs, so I sort of just cribbed the knowledge I have from more C type languages to structure the project. And maybe I didn't really run into a bug, but an incorrect understanding of the standard on my part?

**Comment by shirok** [comment]
You're correct on the recommended way.  Unfortunately the way to setting load paths isn't standardized so you have to dig each implementation's manual.  For Gauche, you can use a command-line option or an environment variable `GAUCHE_LOAD_PATH`.

And it is still a bug, undetected until now because the recommended way doesn't trigger this bug.

**Comment by shirok** [comment]
Fix pushed.
