### ISSUE TITLE
The rest argument list is incompatible with srfi-101 ra-list.

### ISSUE THREAD

**Issue by nkoguro** [shirok/Gauche#566]
After srfi-101 is loaded, map/for-each fails for the list of rest arguments.

```
gosh> (use srfi-101)
gosh> (define (f . args) (map values args))
gosh> (f 1 2 3)
*** ERROR: Invalid assumption: (ra-proper? ra)
```

Installing slib (at line 29 in mklibcat.scm) fails due to this problem.

**Comment by shirok** [comment]
Aaarrrgh.  """(use srfi-101)""" shadows tons of primitive list operators (even `quote`) so anything can happen afterwards.

Is """srfi-101""" automatically loaded during the process?

**Comment by nkoguro** [comment]
Yes.
```
% /home/naoki/.local/bin/gosh -ftest
gosh> (use slib)
gosh> for-each
#<subr (ra-for-each 1 #(#<closure (#f proc)> #<closure (#f proc ra)> #<closure (#f proc . ras)>))>
```
But I don't know where srfi-101 is loaded in slib. I can't find (use srfi-101) or (use scheme.rlist) in slib.scm.

**Comment by shirok** [comment]
Found it.  In slib/require.scm, it scans all available srfis and eval `(cond-expand (srfi-N #t) (else #f))` so that it can respond to `slib:provided?`.  But mere `cond-expand` triggers loading of the named srfi.

Hmm... I could make an exception in `cond-expand` not to load `srfi-101`, which technically violates the spec...  I guess this is a shortcoming of `cond-expand` in the age of R[67]RS.

**Comment by shirok** [comment]
How about now?

**Comment by nkoguro** [comment]
I can install slib with acdc1fc47.
Thanks!
