### ISSUE TITLE
line-edit does not recognize some expressions as complete

### ISSUE THREAD

**Issue by pclouds** [shirok/Gauche#683]
From https://github.com/ashinn/chibi-scheme/issues/629

```
gosh$ (define x '#0=(a . #0#))
......
```

This is a complete form and gosh should evaluate instead of waiting for more. With `GAUCHE_READ_EDIT` unset, it's not a problem, of course.

We probably want some escape hatch here (e.g. press this to evaluate anyway) in unexpected cases like this, besides fixing to accept the above form.

**Comment by shirok** [comment]
Right.  A long-term plan is to modify `read` to add "syntax check" mode---that is, no constructing of objects, nor side effects--so that we share the same parser.  However, it'll take some time.

Which key binding do you think is good to "commit input unconditionally"?   Two contiguous RETURN at the end of input would work?

**Comment by pclouds** [comment]
Two returns may interfere with pasting multiline definitions. Perhaps one of those scheme-send-... bindings in emacs scheme mode. maybe C-M-x.

**Comment by shirok** [comment]
Bind C-M-x to `commit-input` (at least for now).  Closing.
