### ISSUE TITLE
Support sqlite3

### ISSUE THREAD

**Issue by pclouds** [shirok/Gauche#694]
Gauche comes with *dbm support, but no RDBMS. Having something like sqlite3 out of the box would be fantastic for experimenting or quick scripting. We can start with a DBI driver for it. Then depends on demands we could add sqlite-specific APIs to make full use of it.

I started doing something like this, slowly. But it's probably a good idea to check first. If Shiro is against it, I should drop it now. (Yes I know there are some external sqlite3 binding around, but I'd still like the idea of having gauche bundling it).

**Comment by shirok** [comment]
I'm not against it, but one thing is that I want to keep external dependency of Gauche core to minimal.   The idea is that anything that depends on third-party library will be an extension package, assuming that a simple package management system will make it a snap to install it.

`dbm` is an exception, since I needed a robust key-value persistent store and virtually every unix had some kind of dbm back then, for it was used by NIS, MTA, etc.

Now that sqlite3 is kind of replacing dbm, so it is certainly an option that we make sqlite3 "de facto" default database library.  But it is difficult to cut off dbm, for it's been there for long time.  I can think of three options:

- Bundle sqlite3, make dbm extension package at a timing of 1.0 release
- Just bundle sqlite3 as well
- Put effort into a package manager so that it'd be easy to pull and install Gauche-sqlite3.

In a long term I think package manager solution is the best bet.  But I hear needs of others.

**Comment by pclouds** [comment]
A package manager may be the best (I'd rather avoid updating configure.ac; even thought about a two-phase build system where configure.ac is only about gosh, the rest will be configured with gauche.configure after gosh is ready).

Anyway, the biggest problem with packaging is the registry, isn't it? Hunting down where to find a package is no fun. I suppose if you could host it on practical-scheme.net, then we can reuse snow protocol, adjusting it a bit to fit gauche packages (I don't think it supports compiling). Adding a client should be relatively simple...

**Comment by lassik** [comment]
Please check with the schemepersist project / mailing list. There are some plans for a common DB interface.

* https://github.com/schemepersist
* https://srfi-email.schemers.org/schemepersist/

**Comment by lassik** [comment]
Re: packaging, we should eventually decide on a common package metadata format and establish `pkg.scheme.org` or something to serve up packages.

The snow-forg.org metadata files are nice and simple; that format could be used as a starting point for a common design. Not sure how akkuscm.org metadata looks.

**Comment by lassik** [comment]
Re: sqlite and databases, I wrote a small C driver program that embeds SQLite and talks to a Scheme parent process using binary S-expressions. So the Scheme interpreter doesn't need to link to SQLite (or any other database library - postgres/mysql), it only needs to read and write s-expressions. This was done as part of schemepersist work and should be polished eventually. I also started a similar postgres driver written in C.

This is not ideal for the case where Gauche is embedded into a C program, in which case you'd probably want to embed the SQLite C library in the same process as Gauche and the host program. But it's good for a generic database-engine-independent API. Backends for new engines can be added simply as C programs. And if the DB driver crashes, it doesn't take the Scheme program down with it.

**Comment by pclouds** [comment]
I'm aware of schemepersist. However this is about Gauche DBI interface. If one day a common DB interface is realized, then Gauche can have some sort of bridge between its DBI and the common one, but I don't think I'm going to wait for the common one first.

**Comment by pclouds** [comment]
> we should eventually decide on a common package metadata format and establish pkg.scheme.org or something to serve up packages.

this may end up as hard as standardizing ffi. Portable packages are solved by snow, but once you get to compilation (potentially with ffi code), every scheme does it differently.

**Comment by lassik** [comment]
Fully portable packages will be hard indeed. But we could start by simply hosting non-portable packages on a common website, with the hope of eventually making those packages more portable. The package metadata format can and should support implementation-specific extensions, similar to how `define-library` supports `cond-expand`.

**Comment by lassik** [comment]
(My general belief is that simply by having people work in a shared space, they will eventually start collaborating more by themselves. That's why it would make sense to have a common index and server even for non-portable packages. Plus users would have an easier way to find out what the "total set" of all Scheme packages is, and discover new implementations etc. SRFI mailing lists and GitHub would seem to bear out to some extent that this kind of approach is not futile.)

**Comment by shirok** [comment]
The reason I've been putting off package registry (aside from the wiki page) is that I kind of waiting the common Scheme packaging thing to be materialized (snow could grow into one, though it's not very active... writing truly portable Scheme code is still a high-bar.)

One thing I think a good start point is a metadata broker.  A common query service that points to an appropriate repo for the package.  For Gauche, I'm thinking that not "hosting" the package files in one place, but rather keeping a metadata that points to a repoistory (e.g. github) of the package.  It takes effort to maintain packages up to date if we have a central repository, since each package author may forget to push a new release, or silently abandon it and ownership gets vague.

**Comment by lassik** [comment]
Perfect! Your goals exactly match our goals. (I can't recall exactly who "us" is, but I talked about this package index to a few people and there was general agreement that it's probably a good thing.) This motivates to work on it faster.

Let me know (both of you) if you want to help with the design. I don't know what would be a good forum for the discussions. Maybe "schemedoc" mailing list would be better than nothing for now since that's the only place AFAIK where Scheme aggregators are currently discussed.

**Comment by lassik** [comment]
We can already admin scheme.org and have a server; it would just be a matter of designing and writing the software (which is not a trivial matter :)

**Comment by lassik** [comment]
As for the common DBI at schemepersist, @hga has been mainly working on the spec and exploring a Chibi implementation; I have started the subprocess implementations. Gauche's DBI would be a very valuable guide for designing it. Perhaps Harold has looked at it already.

**Comment by hga** [comment]
I have indeed looked at Gauche's DBI for the sdbi project, the major issue is that it uses Gauche's object system, and objects are another thing the Scheme community doesn't agree upon.  Stepping back a bit, it's a useful guide to some of the partitioning of sdbi, at the highest level, specific database adapters can be plugged into the top level database common interface, common to the point of accommodating non-SQL query languages like Cassandra's, which is at the "Hello, world." stage, and the graph standard in progress.

All that said, while I'm at this very moment writing a cloud backup system that uses a RDBMS for caching through my skeletal sdbi, which will advance sdbi somewhat, COVID-19 has put on indefinite hold any targets for finishing sdbi or other schemepersist projects by myself, my plate is just too full unless someone has some serious blocks of time they'd like to devote to it.

**Comment by pclouds** [comment]
Quick note on a "common package format" that's at least suitable for gauche. I probably should open a new issue instead of reusing this one, but once the format is more or less ok, we probably need to reach a wider audience.

For reference, snow format is described [here](http://snow-fort.org/doc/spec/)  gpd file [here](https://github.com/shirok/Gauche/blob/master/lib/gauche/package.scm#L56)
 and ebuild [here](https://dev.gentoo.org/~zmedico/portage/doc/man/ebuild.5.html)

I will probably come back and edit this comment to add more info

---
About snow

- each library in a package depends on a list of other _libraries_. This makes things interesting if multiple packages can provide the same libraries, which ones to choose.

- we may need to depend on specific version of a package, or a range of version like `> 1.2.0` Chibi also has something called 'foreign-depends', haven't checked that out yet.

- of course we would need some form of cond-depends, if a package is specific to a scheme implementation, it should depend on the same feture symbol that `cond-expand` provides on that platform. Other features restriction could also be useful (e.g. if the package can only run with full numeric tower...

- licenes field in the library probably can accept  string for custom licenses

- per-library (or per-program) version seems weird. I would assume most of the time people only need package's version.

---

now on gauche gpd files

- gauche depends on packages instead of libraries/modules inside it (and support limiting by version), this sounds better to me

- providing-modules is kinda the same as library definitions in snow. How to find the library is implied (snow specifies a path to .sld file)

- missing some info needed for metadata broker like package size or hashes, could be stolen from snow

---

something from ebuild (gentoo package description) because I'm more familiar with it

- for build-based packages there should be a number of standard "steps", e,g. unpack, configure, compile, test and install. Many of these steps have standard implementation, but the package can provide different ones if its build process is more complicated

- I suppose we should stick to defining these steps as executable programs. They could be shell scripts, or scheme programs. Up to the packagers 

- dependency specification in gentoo is really detailed, but as long as we can extend the format later, we can just stick to simple one such as `==`, `<`, `>=`...

- package format version should be included in the package description (in Gentoo it's called EAPI) this allows us to evolve the package format while maintain compatibility with existing packages

**Comment by pclouds** [comment]
Closing. chibi-snow does support chibi-ffi, and I'm thinking adding ffi for gauche is not out of question (as long as you stay with simple ffi packages, not something like gtk+ bindings). Then, we could integrate the snow client in gauche (its being mostly r7rs should help).

I'm going to stay away from format changes required for something like gtk+ until all the little improvements have been done. It's really ugly to mix shell and unix commands for more complicated compile/install process, but without a common "high level posix" api, so to speak, we just have to fallback to shell.

**Comment by shirok** [comment]
ffi is one item potentially I want to put in before 1.0.  An easy path is libffi, but it adds another dependency..

**Comment by pclouds** [comment]
Ah you mean pure scheme ffi? I was thinking about the precompiler and stub files that mix C and Scheme.

**Comment by shirok** [comment]
Yes I meant that.  Streamlining generating stubs may be a bit more reachable.

**Comment by johnwcowan** [comment]
Gtk-server, despite its name, is an outboard program that makes it possible to invoke arbitrary shared libraries with a C interface from any language you like.  You specify libraries to be loaded into the server and can then send request/response lines that provide access to the procedures in the library through a variety of protocols: pipes, named pipes (Posix or Windows), TCP, UDP.  A plain text configuration file specifies for each callable procedure what the argument and return types are.  It looks really nice for doing arbitrary things from an interpreter without needing an FFI.

**Comment by shirok** [comment]
@johnwcowan It's very interesting.  We have Gauche-tk, a small pure-Scheme library that allows a Gauche script to run Tk widget sets but in fact it invokes wish (Tcl/Tk shell) and communicates with pipe (from Scheme side, everything goes through proxy object so you won't see the process separation)    Probably I can make Gauche-gtk-server in similar way, and it will come with lots of nice stuff.

Regarding FFI, I'd like to have built-in one in Gauche anyway, without introducing additional dependencies to external libraries.  The lowest layer is already working on Linux/x86_64---you can parse C header file and call C functions with some basic arguments/return values.

**Comment by pclouds** [comment]
I think the bigger problem with FFI (or at least C FFI) is the complex data input in structs (and worse pointers) Doing that purely from scheme is possible but really painful (we could easily get ABI wrong)
