### ISSUE TITLE
How to add R7RS module for a new library?

### ISSUE THREAD

**Issue by lassik** [shirok/Gauche#710]
Can you add an example to `HACKING.adoc` about how to add a new R7RS library and have it registered and installed?

**Comment by lassik** [comment]
What I mean is, for any SRFI nnn, there are two files:

* `lib/srfi-175.scm` -- manually written
* `lib/srfi/175.scm` -- automatically generated

If the second file is missing, it can be loaded as a classic Gauche module, but not as a R7RS library. What's the right way to generate the second file?

**Comment by lassik** [comment]
Aha, we need to add the SRFI at the end of `src/srfis.scm` and then run `gosh src/srfis.scm .` followed by `./DIST gen` and `make`.

**Comment by lassik** [comment]
(I've been working on the last call of SRFI 193, that's why the question :)

**Comment by shirok** [comment]
Yes, `src/srifs.scm` is the central registry.  We have an unresolved issue, though.

I don't want to add entry to `src/srfis.scm` until a srfi is finalized (for it also generates the documentation), but until I add the entry, it can't be loaded with `(import (srf N))`, and testing draft srfis becomes a bit tedious.  That's why I'm thinking to make `srfi/N.scm` a main file and `srfi-N.scm` to be generated.  
https://github.com/shirok/Gauche/issues/680

**Comment by shirok** [comment]
Looks like I can close this.  If you have ideas about managing srfi/N.scm or src/srfis.scm update, use https://github.com/shirok/Gauche/issues/680
