### ISSUE TITLE
Importing .sld files

### ISSUE THREAD

**Issue by tizoc** [shirok/Gauche#72]
Gauche's (0.9.4) `import` doesn't recognise files with the `.sld` extension.

I see that it is part of the list of load suffixes here: https://github.com/shirok/Gauche/blob/2e21daa0a11dabc23d46a904aa74c95e8453ba99/src/load.c#L1224

but `import` ignores that. Also, it would be good if `.sld` files had more precedence than `.scm` files (because `.sld` files usually contain `define-library` declarations that then include a `.scm` file of the same name containing the actual implementation).

**Comment by shirok** [comment]
You mean R7RS `import`?  It does already recognize .sld extension in HEAD.  It delegates loading to Gauche's native `require`, so whatever `require` recognizes, R7RS `import` recognizes.

On the precedence of .sld and .scm.... hm, I think I made it so assuming the case that Gauche-specific wrapper (*.scm) loads generic R7RS library (*.sld).   Since the reverse, generic R7RS library loads Gauche-specific files, doesn't make sense (it's no longer generic).  But I haven't had the actual use case yet.  Do you have pointer to some existing libraries that loads *.scm form *.sld?  Then I can see clearer picture, I guess.

**Comment by tizoc** [comment]
Yes, sorry. All this is in the context of R7RS. I'm running 0.9.4, not HEAD, but that explains why the code is here on Github but my version is not behaving like that.

Regarding precedence, I don't know how widespread it is, and now that you asked for examples I investigated a bit and apparently it is not as common as I believed.

My assumptions come all from chibi-scheme. It tries with `.sld` first and some internal code is defined in the way I mentioned (`.sld` defining the library/interface with `define-library` and a `.scm` file containing the implementation gets `include`d). Look at files that have the same name but different extension:

https://github.com/ashinn/chibi-scheme/tree/master/lib/scheme

I follow the same approach here:

https://github.com/tizoc/chibi-shen/tree/master/shen

I'm working on a local branch, doing some cleanup and making changes to make Shen work in other R7RS implementations (starting with Gauche), that was when I found `.sld` files weren't being loaded (in 0.9.4).

For portability, I'm probably going to get rid of the `.sld` extension in my code because apparently the `.sld` syntax extension isn't widespread yet.

**Comment by shirok** [comment]
I see.  Thanks.  I'll ask Alex why he chose that; I do like the separation of interface and implementation in Chibi, but since the "include" explicitly writes out the extension, we can use non-conflicting name just as well.  It'll be better to settle on consistent convention before it gets widespread.

**Comment by shirok** [comment]
Switched precedence.
