### ISSUE TITLE
Add missing procedures to the <tree-map> to be symmetric with the <hash-table>

### ISSUE THREAD

**Issue by volodymyrprokopyuk** [shirok/Gauche#755]
Hi,

Is there any reason that the `tree-map comparator args ...` and `tree-map-find tm pred :optional failure` procedures are not provided while the corresponding `hash-table-r7 comparator args ...` and `hash-table-find ht pred :optional failure` are already provided? Could you, please, consider providing the missing `tree-map` and `tree-map-find` procedures for the symmetry of the interfaces between the `<hash-table>` and the `<tree-map>`?

Maybe it makes also sense to define the following aliases in order to add the missing procedures to the `<tree-map>` for the sake of symmetry between  the `<hash-table>` and the `<tree-map>`
```scheme
(define tree-map-contains? tree-map-exists?)
(define tree-map-size tree-map-num-entries)
```

**Comment by shirok** [comment]
Ah, I see.  The reason is that tree-map API is symmetric to the original Gauche has-table API, whereas the procedures you mentioned were added later only to support newer SRFI & R7RS.   I'm kind of putting off adding similar API to other datatypes, for it could lead API bloat; `tree-map` isn't portable anyway, so whoever uses it is committing to Gauche API.  Besides, it won't stop at `tree-map`; there are other container types, and shall we adapt every one of them to follow the protocol?

That said, I see it could be confusing to newcomers who look at the current API without historical context.  Since `tree-map` is particularly similar to `hash-table`, it may be reasonable to keep two APIs highly symmetric.

I see issues though.  The optional failure argument of `hash-table-find` is solely to support R7RS/SRFI-125 `hash-table-find`, which has the first two arguments reversed (unfortunately!).   If you need the failure thunk, you should use R7RS API (or built-in `hash-table-find-r7`), rather than built-in `hash-table-find`.  Adding optional failure thunk in `tree-map-find` encourages rather deprecated usage.  Regarding variadic constructor, we have built-in `hash-table` and `hash-table-r7`---if we have `tree-map` variadic constructor, which should it follow?

Now that we have `scheme.mapping` and `scheme.mapping.hash` which provides portable and symmetric API, I tend to encourage users to use them, rather than enhancing Gauche-specific APIs.  Unless there comes a tree-map SRFI, or other convincing reason comes up.  (One drawback is that `scheme.mapping` isn't guarantee in-place mutation, so not all traditional code can adopt it straightforwardly.)

This is not a final decision, so feel free to tell me experiences or use cases that may convince me otherwise.  Since I already know the history, I can't judge from the viewpoint of users who begins to use Gauche now.

**Comment by volodymyrprokopyuk** [comment]
Hi Shiro! Thank you for the extended context and the background behind the Gauche's dictionary APIs!

My motivation and main reasons behind the above proposal are
* Practicality + uniformity + symmetry. For the dictionary API I prefer Gauche's approach over the R7RS, as Gauche's API is more concise and better designed for solving real-world problems (e. g. `hash-table-get` vs `hash-table-ref` or larger `hash-table-ref/default`). But differences in the Gauche's dictionary API are quite annoying, as I have to remember when to use `...-exists?` vs `...contains?` or `...-size` vs `...-num-entries`.
* Symmetric and convenient variadic constructors for both `hash-table` and `tree-map`. I like convenience of the `hash-table`'s variadic constructor as implemented by current `hash-table-r7`, but the `tree-map` does not provide this constructor. So it would be very convenient to have the `tree-map-r7` as in the initial proposal
* Favor practicality over portability. I could start using the `scheme.mapping` API with the symmetric API that does have the `mapping-find` method, but in this case I'd have to refuse the sweet Gauche's dictionary API. The point is to just fill the gap with the Gauche's API (e. g. missing `tree-map-find` procedure) and continue to happily use the practical and very convenient Gauche's API. Anyway, Scheme code portability is challenging given the number of scheme implementations. So what really matters is a complete (without gaps) and convenient (practical) native interface rather than portability issues. I hardly see implementing a system that works on Gauche, Guile, Chez...

Taking advantage of your attention here, I'd like to know you opinion about extending eager comprehensions for the `hash-table` and `tree-map`. I'm planning to do this exercise and let you know about the results. Would you consider adding eager comprehensions for dictionaries to Gauche for practicality and convenience?

**Comment by volodymyrprokopyuk** [comment]
Hi Shiro,

Following your recommendation I'll use portable and symmetric `scheme.mapping` and `scheme.mapping.hash` R7RS APIs.

Thank you for your advice!
