### ISSUE TITLE
Export slot accessors from a module

### ISSUE THREAD

**Issue by volodymyrprokopyuk** [shirok/Gauche#760]
Hi Shiro,

How slot accessors (getter and setter) can be exported from a module?

./hr.scm
```scheme
(define-module hr
  (export <employee>))

(select-module hr)

(define-class <employee> ()
  ([name :init-keyword :name :init-value "nobody" :accessor name]))
```
gosh -I . ./main.scm

```scheme
(use hr)

(let ([e (make <employee> :name "Vlad")])
  (set! (name e) "Volodymyr")
  (print (name e)))
```

I've tried `(export <employee> name)` and `(export-all)` with no luck. The error I get is

```
*** ERROR: no applicable method for #<generic |setter of name| (0)> with arguments (#<<employee> 0x7f7fa1ff6640> "Volodymyr")
```

Thank you very much in advance!

**Comment by shirok** [comment]
Exporting `name` form `hr` should work.   Your code fragments worked for me, so I guess there's something else that caused the error.  Maybe another module is involved?

Actually, CLOS-style accessor method doesn't go well with Scheme-style module system, and weird errors as you mentioned can happen depending on dependency of modules.  So I no longer use accessors.  I should've changed the document to prominently say so.  My recommendation is to avoid accessor method altogether--use `~` to access slots.

----

The reason: Common Lisp's package system is based on the **symbol**, while Scheme's module system is based on the **binding** (or, identifier, in the context of hygienic macro).

When the accessor method is created, it checks if there's a generic function of the same name has already defined.  If so, a method is added to the gf.  If not, a new gf is created and bound to the name, then a method is added to it.

Suppose you have module A and B, both defines a class that has accessor `name`:

```
(define-module A
   (export <A> name)
   (define-class <A> ((name :accessor name))))

(define-module B
  (export <B> name)
  (define-class <B> ((name :accessor name))))

(use A)
(use B)

name ;;=> ?
```
When the class `<A>` is defined, it looks for a gf named `name`.  There isn't, so a new gf is created and bound to `name`, withih the module `A`.   The same happens in module `B`.  So, two methods actually attached to different gfs.

If you use two modules, `name` imported from the latter module silently shadows the former.  So the last reference of `name` returns a gf created in module `B`, which doesn't know about `<A>`.

In CL, the global value of a variable is directly stored in the symbol itself.  So if two `name` belong to the same package, they share the gf.   If they belong to different packages, they look different from the user side--e.g. `A:name` and `B:name`--so there's no confusion.

The same problem could happen with ordinary methods created by `define-method`, but in practice it is less of a problem, for such methods tend to be named distinctively, e.g. `employee-name` etc.  On the other hand, accessor name tends to be succinct and likely to conflict.

I've tried to fix this issue but couldn't find a clean solution yet.   If you inspect Gauche internals you might've noticed a module `gauche.gf`.   One time I used the module to keep such automatically created gfs so that the y are shared implicitly.   But there are cases that you don't want that behavior and I abandoned the idea.

**Comment by volodymyrprokopyuk** [comment]
Hi Shiro,

You are absolutely right! I my case happened exactly what you described above. I have two classes in distinct modules with the same accessor which got shadowed, hence the error.

Changing the name of the accessor in one of the classes resolves the problem! The solution you mentioned of using  `~` does not face the reported problem at all and should be preferred way to access slots.

I'd recommend to reflect in the documentation the preference of the general accessor `~` over the `:accessor` generic function for slot access given the above discussed set of potential errors when importing classes with the same accessors from different modules.

Thank you very much!

**Comment by pclouds** [comment]
>  I should've changed the document to prominently say so. 

Even better if you kept most of what you wrote in there :) Fascinating.

**Comment by shirok** [comment]
One of the advantages of gfs and methods is that you don't need to worry about name conflict, so it kind of sucks that our module system hinders that advantage.   But I now see this gap is inherent.

The similar issue recently arose in SRFI discussion.   Some macros needs auxiliary keywords, such as `else`.  If two unrelated libraries want to export such keyword with the same literal name, what should happen?   In CL-style, literal symbol match, there's no problem, but if keywords are matched hygienically, two auxiliary keywords with the same name would be different.    SRFI-206 is created to address the issue, but it employs some magic (automagically creates bindings by `import`).

**Comment by volodymyrprokopyuk** [comment]
The GFs feature of being free from name conflicts is very valuable to the language and ideally should be preserved in reliable and portable way when dealing with multiple modules. If the current module system does not allow for this, either the module system should be altered or new mechanisms should be added. I'm not yet in the position due to my level of understanding to advice on possible solutions
