### ISSUE TITLE
SRFI-217 implementation issue (performance or infinite loop?)

### ISSUE THREAD

**Issue by jpellegrini** [shirok/Gauche#796]
Hello,
The implementation of SRFI-217 seems to work correctly, but when I try to load 2000000 items in an integer set, it apparently enters an infinite loop.

See this program:

```scheme
(use srfi-9)
(use srfi-27)
(use srfi-143)

(use srfi-217)

(define (riset MAX)
  (let loop ((n 0) (s (iset)))
    (if (= n MAX)
        s
        (loop (+ 1 n)
              (iset-adjoin s (random-integer MAX))))))

(define s #f)
(time (set! s (riset 2000000)))
```

With the current implementation, it takes more than one hour and does not finish. I had to hit `^C`

```
gosh$ (time (set! s (riset 2000000)))

^C*** UNHANDLED-SIGNAL-ERROR: unhandled signal 2 (SIGINT)
Stack Trace:
_______________________________________
  0  (maybe-copy tmap)
        at "/usr/local/share/gauche-0.98/0.9.11_rc4/lib/srfi-217.scm":190
  1  (maybe-copy tmap)
        at "/usr/local/share/gauche-0.98/0.9.11_rc4/lib/srfi-217.scm":190
  2  (%adjoin-1! k (iset-tmap input) noclobber)
        at "/usr/local/share/gauche-0.98/0.9.11_rc4/lib/srfi-217.scm":208
  3  (iset-adjoin s (random-integer MAX))
        at "(input string port)":6
  4  (riset 2000000)
        at "(input string port)":1
  5  (eval expr env)
        at "/usr/local/share/gauche-0.98/0.9.11_rc4/lib/gauche/interactive.scm":336
```

If I load the reference implementation, it takes a little more than one minute (I loaded `trie.scm` and `217.scm` instead of doing `use srfi-217`):

```
gosh$ (time (set! s (riset 2000000)))
;(time (set! s (riset 2000000)))
; real  54.877
; user  71.900
; sys    0.480
#<<iset> 0x7f572b8f6520>
```

Perhaps there is some subtle issue in the implementation, leading to an infinite loop? Or maybe to exponential running time?

**Comment by jpellegrini** [comment]
I forgot to include the version:

```
Gauche scheme shell, version 0.9.11_rc4 [utf-8,pthreads], x86_64-pc-linux-gnu
(version "0.9.11_rc4")
(command "gosh")
(scheme.id gauche)
(languages scheme r5rs r7rs)
(encodings utf-8)
(website "https://practical-scheme.net/gauche")
(build.platform "x86_64-pc-linux-gnu")
(build.configure "--enable-multibyte=utf-8")
(scheme.path "/usr/local/share/gauche-0.98/site/lib" "/usr/local/share/gauche-0.98/0.9.11_rc4/lib")
(gauche.threads pthreads)
(gauche.net.tls axtls mbedtls)
```

**Comment by shirok** [comment]
Our current implementation is based on the built-in mutable tree-map, and favors linear-updating operations rather than functional operations.   If you call functional API that changes the set, the entire tree map is copied.

If you change `iset-adjoin` to `iset-adjoin!`, it runs reasonably fast.

```
gosh> (time (set! s (riset 2000000)))
;(time (set! s (riset 2000000)))
; real  14.358
; user  14.540
; sys    0.020
```

If functional use is popular, I'd change the internal representation.   However, the gievn example---constructing a set by adding elements one by one---is the most taxing operation for the functional interface, and linear updating API exists for this kind of usage.  Even Clojure, which is based on immutable data, provides a transient data structures (controlled mutability) precisely to handle this kind of case.

I'd like to know more about use cases.   If this kind of use case is inevitable, I'll change the implementation.

**Comment by jpellegrini** [comment]
> I'd like to know more about use cases. If this kind of use case is inevitable, I'll change the implementation.

Oh, I don't have a compelling use case; I can change to the linear update version easily for what I had in mind.   I opened the issue because I noticed that the functional API of the reference implementation was faster. If the functional interface isn't a priority, that's OK (and in that case I apologize for opening this issue).

**Comment by shirok** [comment]
Oh don't apologize.   This is a useful data point.   If people tend to use functional interface, it is a good reason for us to reconsider implementation.

Typically, functional interface only partially copy the internal data structure and share the persistent parts.  It works well if you only use functional data structures (that is, linear-updating version is only an alias of functional versoin).   If you allow mutation, however, you need extra bookkeeping, for you can't mutate a part that is shared.   In a SRFI mailing list, 
Marc Nieper-Wißkirchen outlined an efficient way to implement one that allows both functional and mutable data.

Since the underlying tree map is implemented in C and used from several other internal parts, it'll take time for us to adopt Marc's idea.  Meanwhile we may be able to alleviate the problem with auxiliary structure, e.g. we keep fixed size of "buffer", and adding an item creates a new structure that shares the input tree map but place the new item in the buffer.   If the buffer gets full, we copy the tree map, incorporating the content of the buffer.   We need to benchmark to see how much it is effective; it doesn't reduce the order of time complexity, but can speed up the extreme case like the one in this issue by a constant factor.

**Comment by jpellegrini** [comment]
> If you allow mutation, however, you need extra bookkeeping, for you can't mutate a part that is shared

Ah, ok. My interpretation of 'linear update' was that it would be the programmer's responsibility to not let that happen,

"_So clients of these procedures write in a functional style, but must additionally be sure that, when the procedure is called, there are no other live pointers to the potentially-modified iset_",

But I understand that it would be nice to have this checked by the runtime, as Gauche is doing.

> Marc Nieper-Wißkirchen outlined an efficient way to implement one that allows both functional and mutable data.

I couldn't find that. Was it in the SRFI-217 mailing list, or another one?

**Comment by shirok** [comment]
> Ah, ok. My interpretation of 'linear update' was that it would be the programmer's responsibility to not let that happen,

It's subtler than that.

Suppose each iset keeps its elements as a list (very inefficient, but possible). Let's write an iset as `{ list }` for now; e.g. `(iset 1 2 3)` returns `{ (1 2 3) }`. 

When we call functional `(iset-delete { (1 2 3) } 1)`, it can return `{ (1 2) }`, where the internal list `(1 2)` directly points the cdr of the original list `(1 2 3)`.  It doesn't need to copy the entire list.  If we use a tree instead, functional updating only needs to copy log n nodes, and that's why functional interface is "not so bad" but still less efficient than linear updating interface, which can do it without allocation.

However, see the following code: 

```
(let ((y (iset-delete x 1)))
   (iset-delete! y 3)) 
```

`y` isn't used anywhere other than passed to `iset-adjoin!`, so it should be legitimate use of linear-updating inetrface.   However, if `iset-delete` returns an iset, which itself is "fresh" but its internal structure is implicitly shaerd with other isets, then linear-updating operation can't mutate the internal structure.  

The discussion is here:  https://srfi-email.schemers.org/srfi-224/msg/16764342/

**Comment by jpellegrini** [comment]
Oh, right, I see the point. So I suppose that, since the behavior is already expected (because the test code I used was not using the SRFI in the way you had thought, etc) then this issue could be closed?

**Comment by shirok** [comment]
Let's close it.   Whenever you hit a performance issue, feel free to open a new issue.

**Comment by jpellegrini** [comment]
Ok! And thanks for your patience.
