### ISSUE TITLE
should have r7rs flush-output-port (now using flush)

### ISSUE THREAD

**Issue by dufresnep** [shirok/Gauche#813]
End of 6.13 of r7rs have:
"(flush-output-port) procedure
(flush-output-port port) procedure
Flushes any buffered output from the buffer of output-port
to the underlying file or device and returns an unspecified"

now using flush and flush-all-ports (6.21.8.5 Low-level output ... in the manual)

**Comment by shirok** [comment]
It does.
https://practical-scheme.net/gauche/man/?p=flush-output-port

**Comment by dufresnep** [comment]
Oh I see.

I have to go from:

#! /usr/bin/env gosh
(display "Enter a number:")
(flush)
(read-line)

to:

#!/usr/bin/env gosh
(define-library (number)
  (import (scheme base))
  (begin
    (write-string "Enter a number:")
    (flush-output-port)
    (read-line)))

**Comment by shirok** [comment]
Doesn't need to fully transform to portable R7RS.  It's just a namespace, so you could just add `(use scheme.base)` to the original Gauche scirpt.

But this made me think---since more and more people become familiar with R7RS and naturally expect `flush-output-port`, maybe we can just have that alias in `gauche` module as well.
