### ISSUE TITLE
AOT Compilation

### ISSUE THREAD

**Issue by stew-j** [shirok/Gauche#833]

**Comment by shirok** [comment]
We already have `eval-when`, but undocumented.  It was added as a quick hack to make Gauche compile itself, and not tested on other cases.  I suspect I need more work to make sure it work as expected.

Regarding AOT compliation, there are a few different aims:
- Making loading fast - we already have this.  See doc/HOWTO-precompile.adoc.  Scheme code is macroexpanded and compiled into VM code, dumped as a static C data, and then made into dymaically loadable `.so` file.
- Making execution fast - by spending more time on optimization.  This is I'm experimenting currently.  You might have noticed that we have commits on lib/gauche/cgen/bbb.scm and lib/gauche/cgen/cbe.scm recently.  At this moment, simple function can be compiled into native code via C, but it is not faster than VM---mainly because of procedure call overhead that is necessary to allow VM code and AOT compiled code mixed freely, including call/cc.
- Having a portable fasl - besides making loading faster, having an architecture-independent fasl file format so that AOT compiled code can be distributed across different platforms.  Currently I'm not considering this goal.  The burden to maintain yet another format doesn't seem to outweigh the merit.
- 
 
-

**Comment by stew-j** [comment]
Thank you for your comments, they were helpful.  I did read the precompile HOWTO.  I probably should have text searched the code-base for ```eval-when```.

> The burden to maintain yet another format doesn't seem to outweigh the merit.
I agree, I'd probably never use it.

For a use case in my CL code for ```eval-when``` see:

https://github.com/JMC-design/tovero/blob/master/examples/turtle-clive-shader.lisp#52

This allows me to have C ```#include``` like functionality in CL, by querying the wrapped library's RTTI at compile time, only wrapping the classes needed.  This would be nice to keep in my code.
