### ISSUE TITLE
(load) not working in R7RS mode?

### ISSUE THREAD

**Issue by camilledalmeras** [shirok/Gauche#926]
Hello,

Let’s say we have a file named "test.scm" that contains this single line:
(define (say-hello) "Hello world!")

With gosh -r7:
(load "./test.scm")
-> "./test.scm"
(say-hello)
-> *** ERROR: unbound variable: say-hello (stack trace follows)

With guile --r7rs, csi -R r7rs and chibi-scheme, (say-hello) returns the expected "Hello world!"

I’m most certainly missing something obvious, so feel free to berate me accordingly.

Thanks.

**Comment by shirok** [comment]
The issue is not about `load`, but your `test.scm`.   It's not a valid R7RS program.
R7RS code must be either an R7RS library or an R7RS program.  An R7RS library should consist of `(define-library ..)`.  An R7RS program must have one or more `import` form, followed by Scheme declarations / expressions.

If you write `test.scm` as follows, it will work as expected:

```
(import (scheme base))
(define (say-hello) "Hello world!")
```

If the loaded file is neither an R7RS program or an R7RS library, it's up to the implementation how to interpret it.  In Gauche,  we interpret it as a Gauche program, which is by default loaded into `user` module, where all the Gauche core bindings are visible.  On the other hand, the module you're in after `gosh -r7` is `r7rs.user` module, where some of R7RS bindings are visible.  Since your original `test.scm` is loaded into `user` module, it is not visible from `r7rs.user` module.

**Comment by camilledalmeras** [comment]
Many thanks for the clear and thorough explanation, and sorry for the noise. I’m closing the issue.

**Comment by shirok** [comment]
No need to be sorry, but you're welcome.  These kind of questions are very important to know where users get stumbled, and give us hints to improve.
