### ISSUE TITLE
Revive `gauche.test.generative`

### ISSUE THREAD

**Issue by shirok** [shirok/Gauche#953]
It's been back-burnered for years.   Maybe it's time to make it official.

- The name `check` conflicts with SRFI-78, so we'd better rename it.  

- The part of binding geneator output to variables can be done with SRFI-42; we may deconstruct this into "run body many times and stop when test error detected" and "bind variables  with generator output", and delegate the latter to SRFI-42.

**Comment by a2378** [comment]
Can the generative test library use SRFI-194: Random data generators for the data source? That would make it possible to set the random state for deterministic testing.

I have an implementation that extends SRFI-64 and would be happy to help if you are looking for external contributions.

For contributions, do you prefer patches to the mailing list or Github PRs? I sent a patch to gauche-devel yesterday but it may have gotten spam-filtered because I am not a member.

[property-test.sld.txt](https://github.com/shirok/Gauche/files/13923642/property-test.sld.txt)
[property-test-tester.scm.txt](https://github.com/shirok/Gauche/files/13923650/property-test-tester.scm.txt)

**Comment by shirok** [comment]
That looks nice (and you're right about Gauche's `make-random-real`.   It is actually `reals-between$` in `data.random` which was broken).  What I have in mind is to build on top of `gauche.test` and `data.random`, for our srfi-64 and srfi-194 implementations are built on top of them respectively, and having `gauche.test.generative` built on top of those srfis seems overly complex.  However, for the broader Scheme community, a library based on extablished srifs are mroe desirable.

Are you interested in bringing your property-test to srfi?  If there will be one, I'm all to adopt its API. 

Regarding code contributions, github PRs is better.   However, our license is BSD and the contribution needs to be the same or looser license.

**Comment by a2378** [comment]
Sure, I'll draft an SRFI and a relicensed PR for the Gauche implementation.

**Comment by shirok** [comment]
Pushed the fix of `real-between$`.  It should fix `make-random-real`, too.

**Comment by shirok** [comment]
We drop `gauche.test.generative`, in favor of `srfi.252`.
